steps:
  # - name: 'gcr.io/$PROJECT_ID/restore_cache'
  #   args:
  #   - '--bucket=gs://$_CACHE_BUCKET'
  #   - '--key=resources-$(checksum yarn.lock)'
    
  - name: 'node:10-jessie-slim'
    entrypoint: yarn
    args: ['install']

  # - name: 'gcr.io/$PROJECT_ID/save_cache'
  #   args:
  #   - '--bucket=gs://$_CACHE_BUCKET'
  #   - '--key=resources-$(checksum yarn.lock)'
  #   - '--path=node_modules'
  #   - '--path=packages/gatsby-theme-pantheon-core/node_modules'
  #   - '--path=packages/gatsby-theme-pantheon-drupal/node_modules'
  #   - '--path=packages/gatsby-theme-pantheon-wordpress/node_modules'
  #   - '--path=gatsby-drupal/node_modules'
  #   - '--path=gatsby-drupal-dark/node_modules'
  #   - '--path=gatsby-drupal-shadowing/node_modules'
  #   - '--path=gatsby-wordpress/node_modules'
  #   - '--no-clobber'
  
  # - name: 'gcr.io/$PROJECT_ID/restore_cache'
  #   args:
  #   - '--bucket=gs://$_CACHE_BUCKET'
  #   - '--key=resources-$_PATH'

  - name: 'node:10-jessie-slim'
    entrypoint: yarn 
    args: ['build']
    env:
    - WORDPRESS_GRAPHQL=$WORDPRESS_GRAPHQL
    - CI=true

  # - name: 'gcr.io/$PROJECT_ID/save_cache'
  #   args:
  #   - '--bucket=gs://$_CACHE_BUCKET'
  #   - '--key=resources-$_PATH'
  #   - '--path=$_PATH/public'
  #   - '--path=$_PATH/.cache'
  
  
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', '-h', 'Cache-Control:public, s-maxage=15, stale-while-revalidate=300', '-h', 'Content-Disposition', 'rsync', '-r', './public', 'gs://static.pantheonfrontend.website/hello-wpcampus-gatsby/gcp']
    # -m setmeta -r -h "Cache-Control:public, s-maxage=15, stale-while-revalidate=300" -h "Content-Disposition"
  # gsutil -m -h "Cache-Control:private, max-age=0, no-transform" rsync -r ./dir gs://my-bucket